# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 702)
        MainWindow.setMinimumSize(QtCore.QSize(1020, 702))
        MainWindow.setMaximumSize(QtCore.QSize(1020, 702))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/winicon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolgroup = QtWidgets.QGroupBox(self.centralwidget)
        self.toolgroup.setGeometry(QtCore.QRect(10, 10, 251, 521))
        self.toolgroup.setCheckable(False)
        self.toolgroup.setObjectName("toolgroup")
        self.header = QtWidgets.QComboBox(self.toolgroup)
        self.header.setGeometry(QtCore.QRect(110, 49, 131, 22))
        self.header.setEditable(True)
        self.header.setObjectName("header")
        self.label = QtWidgets.QLabel(self.toolgroup)
        self.label.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label.setObjectName("label")
        self.searchbox = QtWidgets.QLineEdit(self.toolgroup)
        self.searchbox.setGeometry(QtCore.QRect(90, 90, 151, 20))
        self.searchbox.setObjectName("searchbox")
        self.label_2 = QtWidgets.QLabel(self.toolgroup)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.label_2.setObjectName("label_2")
        self.filterbtn = QtWidgets.QPushButton(self.toolgroup)
        self.filterbtn.setGeometry(QtCore.QRect(30, 140, 75, 23))
        self.filterbtn.setObjectName("filterbtn")
        self.clearbtn = QtWidgets.QPushButton(self.toolgroup)
        self.clearbtn.setGeometry(QtCore.QRect(140, 140, 75, 23))
        self.clearbtn.setObjectName("clearbtn")
        self.okbtn = QtWidgets.QPushButton(self.centralwidget)
        self.okbtn.setGeometry(QtCore.QRect(470, 580, 75, 23))
        self.okbtn.setObjectName("okbtn")
        self.cancelbtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelbtn.setGeometry(QtCore.QRect(580, 580, 75, 23))
        self.cancelbtn.setObjectName("cancelbtn")
        self.helpbtn = QtWidgets.QPushButton(self.centralwidget)
        self.helpbtn.setGeometry(QtCore.QRect(680, 580, 75, 23))
        self.helpbtn.setObjectName("helpbtn")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(10, 540, 250, 80))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("icons/codelogo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(270, 550, 731, 10))
        self.progressBar.setProperty("value", 1)
        self.progressBar.setObjectName("progressBar")
        self.Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Tab.setGeometry(QtCore.QRect(270, 20, 731, 511))
        self.Tab.setObjectName("Tab")
        self.FormTab = QtWidgets.QWidget()
        self.FormTab.setObjectName("FormTab")
        self.Tab.addTab(self.FormTab, icon, "")
        self.AnalysisTab = QtWidgets.QWidget()
        self.AnalysisTab.setObjectName("AnalysisTab")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/point.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Tab.addTab(self.AnalysisTab, icon1, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.File = QtWidgets.QToolBar(MainWindow)
        self.File.setObjectName("File")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.File)
        self.Edit = QtWidgets.QToolBar(MainWindow)
        self.Edit.setObjectName("Edit")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.Edit)
        self.Data = QtWidgets.QToolBar(MainWindow)
        self.Data.setObjectName("Data")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.Data)
        self.Navigation = QtWidgets.QToolBar(MainWindow)
        self.Navigation.setObjectName("Navigation")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.Navigation)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon3)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon4)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/saveas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon5)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon6)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon7)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon8)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon9)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCreate_DataFrame = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/create.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_DataFrame.setIcon(icon10)
        self.actionCreate_DataFrame.setObjectName("actionCreate_DataFrame")
        self.actionDelete_Record = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_Record.setIcon(icon11)
        self.actionDelete_Record.setObjectName("actionDelete_Record")
        self.actionAdd_Record = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Record.setIcon(icon12)
        self.actionAdd_Record.setObjectName("actionAdd_Record")
        self.actionZoom = QtWidgets.QAction(MainWindow)
        self.actionZoom.setObjectName("actionZoom")
        self.actionOrtho = QtWidgets.QAction(MainWindow)
        self.actionOrtho.setObjectName("actionOrtho")
        self.actionPerspective = QtWidgets.QAction(MainWindow)
        self.actionPerspective.setObjectName("actionPerspective")
        self.actionBack = QtWidgets.QAction(MainWindow)
        self.actionBack.setObjectName("actionBack")
        self.actionFront = QtWidgets.QAction(MainWindow)
        self.actionFront.setObjectName("actionFront")
        self.actionLeft = QtWidgets.QAction(MainWindow)
        self.actionLeft.setObjectName("actionLeft")
        self.actionRight = QtWidgets.QAction(MainWindow)
        self.actionRight.setObjectName("actionRight")
        self.actionBottom = QtWidgets.QAction(MainWindow)
        self.actionBottom.setObjectName("actionBottom")
        self.actionZoom_2 = QtWidgets.QAction(MainWindow)
        self.actionZoom_2.setObjectName("actionZoom_2")
        self.actionZoom_Previous = QtWidgets.QAction(MainWindow)
        self.actionZoom_Previous.setObjectName("actionZoom_Previous")
        self.actionZoom_Window = QtWidgets.QAction(MainWindow)
        self.actionZoom_Window.setObjectName("actionZoom_Window")
        self.actionZoom_Object = QtWidgets.QAction(MainWindow)
        self.actionZoom_Object.setObjectName("actionZoom_Object")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuData.addAction(self.actionCreate_DataFrame)
        self.menuData.addAction(self.actionDelete_Record)
        self.menuData.addAction(self.actionAdd_Record)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.File.addAction(self.actionOpen)
        self.File.addAction(self.actionNew)
        self.File.addAction(self.actionSave)
        self.File.addAction(self.actionSaveAs)
        self.File.addAction(self.actionQuit)
        self.Edit.addAction(self.actionCut)
        self.Edit.addAction(self.actionCopy)
        self.Edit.addAction(self.actionPaste)
        self.Data.addAction(self.actionCreate_DataFrame)
        self.Data.addAction(self.actionAdd_Record)
        self.Data.addAction(self.actionDelete_Record)

        self.retranslateUi(MainWindow)
        self.Tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Timesheet Application ver 1.0.0"))
        self.toolgroup.setTitle(_translate("MainWindow", "Toolbox"))
        self.label.setText(_translate("MainWindow", "Filter by"))
        self.label_2.setText(_translate("MainWindow", "Specify item"))
        self.filterbtn.setText(_translate("MainWindow", "Filter"))
        self.clearbtn.setText(_translate("MainWindow", "Clear Filter"))
        self.okbtn.setText(_translate("MainWindow", "Ok"))
        self.cancelbtn.setText(_translate("MainWindow", "Cancel"))
        self.helpbtn.setText(_translate("MainWindow", "Help"))
        self.Tab.setTabText(self.Tab.indexOf(self.FormTab), _translate("MainWindow", "TMS Form"))
        self.Tab.setTabText(self.Tab.indexOf(self.AnalysisTab), _translate("MainWindow", "Analysis"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.File.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.Edit.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.Data.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.Navigation.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "click to open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "SaveAs"))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionCreate_DataFrame.setText(_translate("MainWindow", "Create DataFrame"))
        self.actionCreate_DataFrame.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionDelete_Record.setText(_translate("MainWindow", "Delete Record"))
        self.actionDelete_Record.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionAdd_Record.setText(_translate("MainWindow", "Add Record"))
        self.actionAdd_Record.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionZoom.setText(_translate("MainWindow", "Zoom"))
        self.actionOrtho.setText(_translate("MainWindow", "Ortho"))
        self.actionPerspective.setText(_translate("MainWindow", "Perspective"))
        self.actionBack.setText(_translate("MainWindow", "Back"))
        self.actionFront.setText(_translate("MainWindow", "Front"))
        self.actionLeft.setText(_translate("MainWindow", "Left"))
        self.actionRight.setText(_translate("MainWindow", "Right"))
        self.actionBottom.setText(_translate("MainWindow", "Bottom"))
        self.actionZoom_2.setText(_translate("MainWindow", "Zoom"))
        self.actionZoom_Previous.setText(_translate("MainWindow", "Zoom Previous"))
        self.actionZoom_Window.setText(_translate("MainWindow", "Zoom Window"))
        self.actionZoom_Object.setText(_translate("MainWindow", "Zoom Object"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
